#! /usr/bin/env sh

ffmpeg \
  -f alsa -ac 1 -i default -acodec aac \
  -i /dev/video0 \
  -codec:v libx264 \
  -pix_fmt yuv420p \
  -profile:v baseline \
  -b:v 500k \
  -s 640x480 \
  -f alsa \
  -codec:a aac \
  -strict experimental \
  -ac 2 \
  -b:a 128k \
  -movflags faststart \
  -map 0 \
  -threads 2 \
  -filter_complex "drawtext=fontfile=FreeSerif.ttf:fontcolor=white:x=10:y=(h-10-text_h):text='%{localtime\:%F %T}:fontsize=14'" \
  -f flv rtmp://192.168.1.133:1935/live/webcam
